const $=selector=>document.querySelector(selector);
let config=null,orderToken="",currentOrder=null,refreshTimer=null;
const labels={payment_pending:"等待付款",payment_submitted:"等待核款",payment_rejected:"付款未通过",paid:"付款已确认",key_issued:"密钥已签发",delivered:"已交付",refund_requested:"售后处理中",refunded:"已退款"};
const messages={payment_pending:"订单已创建，请完成付款并提交核验信息。",payment_submitted:"已收到付款信息，卖家正在人工核验；本页会自动刷新。",payment_rejected:"付款信息暂时无法核实，请检查后重新提交或联系支持。",paid:"付款已确认，正在签发激活密钥。",key_issued:"密钥已签发，正在完成交付。",delivered:"到账已经确认，激活密钥已在本页发放。",refund_requested:"售后正在处理该订单，密钥已停止续租。",refunded:"经售后确认，款项已退回，关联密钥已封禁。"};
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("visible");setTimeout(()=>node.classList.remove("visible"),3200)}
async function request(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(orderToken)headers["X-Order-Token"]=orderToken;const response=await fetch(path,{...options,headers});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body?.error?.message||`请求失败（${response.status}）`);return body}
function setStep(number){document.querySelectorAll(".steps li").forEach(node=>node.classList.toggle("active",Number(node.dataset.step)<=number))}
function showSection(name){["create","payment","status"].forEach(item=>$(`#${item}Step`).hidden=item!==name);setStep(name==="create"?1:name==="payment"?2:3);location.hash=name==="create"?"checkout":`order=${orderToken}`}
function providerById(id){return config?.payment_providers.find(provider=>provider.id===id)}
function displayDate(value){if(!value)return"—";const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short"}).format(date)}
async function loadConfig(){config=await request("/api/checkout/config");const product=config.product;$("#price").textContent=`¥${(product.amount_cents/100).toFixed(2)}`;if(product.refund_policy)$("#refundPolicy").textContent=product.refund_policy;const support=config.support_contact||"售后QQ群：923937311";$("#supportContact").textContent=support;$("#heroSupport").textContent=support.replace(/^售后QQ群[：:]\s*/,"");const choices=$("#providerChoices");choices.replaceChildren();config.payment_providers.filter(provider=>provider.available).forEach(provider=>{const label=document.createElement("label");label.className="provider";const input=document.createElement("input");input.type="radio";input.name="payment_provider";input.value=provider.id;input.required=true;if(!choices.querySelector("input:checked"))input.checked=true;const span=document.createElement("span");span.textContent=provider.label;label.append(input,span);choices.append(label)});if(!choices.querySelector("input")){const warning=document.createElement("p");warning.className="notice";warning.textContent="经营收款渠道尚未配置，请通过售后QQ群联系卖家。";choices.append(warning)}}
function renderPayment(order){const provider=providerById(order.payment_provider);$("#orderId").textContent=order.id;const box=$("#paymentInstructions");box.replaceChildren();const title=document.createElement("strong");title.textContent=provider?.label||order.payment_provider;box.append(title);if(provider?.instructions){const p=document.createElement("p");p.textContent=provider.instructions;box.append(p)}if(provider?.qr_image_url){const figure=document.createElement("figure");figure.className="payment-qr";const image=document.createElement("img");image.src=provider.qr_image_url;image.alt="支付宝经营收款二维码";image.loading="eager";const caption=document.createElement("figcaption");caption.textContent="请使用支付宝扫描经营码，付款金额为 ¥9.90";const link=document.createElement("a");link.href=provider.qr_image_url;link.target="_blank";link.rel="noopener noreferrer";link.textContent="在新页面打开经营码大图";figure.append(image,caption,link);box.append(figure)}if(provider?.payment_url){const link=document.createElement("a");link.href=provider.payment_url;link.target="_blank";link.rel="noopener noreferrer";link.textContent="前往官方经营收款页面 →";box.append(link)}showSection("payment")}
function field(name,value){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=name;dd.textContent=value||"—";return[dt,dd]}
function renderStatus(order){currentOrder=order;clearTimeout(refreshTimer);$("#statusTitle").textContent=labels[order.status]||order.status;$("#statusBadge").textContent=order.status;$("#statusMessage").textContent=messages[order.status]||"订单状态已更新。";$("#statusToken").textContent=orderToken;const fields=$("#statusFields");fields.replaceChildren(...field("订单号",order.id),...field("金额",`¥${(order.amount_cents/100).toFixed(2)} ${order.currency}`),...field("支付渠道",providerById(order.payment_provider)?.label||order.payment_provider),...field("联系方式",order.contact),...field("创建时间",displayDate(order.created_at)),...field("密钥后四位",order.license?.key_suffix?`•••• ${order.license.key_suffix}`:"尚未签发"),...field("售后方式","QQ群 923937311"));const delivery=$("#deliveryKeyBox");delivery.hidden=!order.activation_key;$("#deliveryKeyValue").textContent=order.activation_key||"";showSection("status");if(order.status==="payment_submitted")refreshTimer=setTimeout(()=>refreshOrder().catch(error=>toast(error.message)),10000)}
async function refreshOrder(){if(!orderToken)throw new Error("请输入订单查询 Token");const body=await request("/api/order");renderStatus(body.order)}
$("#orderForm").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{const body=await request("/api/orders",{method:"POST",body:JSON.stringify({contact:data.get("contact"),payment_provider:data.get("payment_provider")})});orderToken=body.status_token;sessionStorage.setItem("labFactoryOrderToken",orderToken);renderPayment(body.order);toast("订单已创建，请保存查询 Token")}catch(error){toast(error.message)}});
$("#paymentForm").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{const body=await request("/api/order/payment",{method:"POST",body:JSON.stringify({payment_reference:data.get("payment_reference"),paid_at:data.get("paid_at")})});renderStatus(body.order);toast("付款信息已提交")}catch(error){toast(error.message)}});
$("#refreshOrder").addEventListener("click",()=>refreshOrder().catch(error=>toast(error.message)));
$("#copyToken").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(orderToken);toast("订单 Token 已复制")}catch{toast("复制失败，请手动保存")}});
$("#copyDeliveryKey").addEventListener("click",async()=>{const key=currentOrder?.activation_key||"";if(!key)return;try{await navigator.clipboard.writeText(key);toast("激活密钥已复制")}catch{toast("复制失败，请手动复制")}});
function openLookup(){$("#lookupDialog").showModal()}$("#openLookup").addEventListener("click",openLookup);$("#footerLookup").addEventListener("click",openLookup);
$("#lookupForm").addEventListener("submit",async event=>{event.preventDefault();orderToken=String(new FormData(event.currentTarget).get("token")||"").trim();try{await refreshOrder();sessionStorage.setItem("labFactoryOrderToken",orderToken);$("#lookupDialog").close()}catch(error){toast(error.message)}});
function enableReveals(){const nodes=document.querySelectorAll(".reveal");if(matchMedia("(prefers-reduced-motion: reduce)").matches||!("IntersectionObserver"in window)){nodes.forEach(node=>node.classList.add("visible"));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});nodes.forEach(node=>observer.observe(node))}
enableReveals();
(async()=>{try{await loadConfig();const fragment=new URLSearchParams(location.hash.replace(/^#/,""));orderToken=fragment.get("order")||sessionStorage.getItem("labFactoryOrderToken")||"";if(orderToken)await refreshOrder()}catch(error){toast(error.message)}})();
